# Hammerspoon Configuration Module for macOS
# Manages Hammerspoon window management and app switching configuration
# Only applies when systemSettings.osType = "darwin" and userSettings.hammerspoonEnable = true

{ config, pkgs, lib, systemSettings, userSettings, ... }:

let
  # Hammerspoon config variant
  configVariant = userSettings.hammerspoonConfig or "default";

  # Generate Lua code for app bindings
  generateAppBindings = bindings: lib.concatMapStringsSep "\n" (binding:
    if binding.action or "" == "cycleApp" then
      ''hyper:bind({}, "${binding.key}", function() cycleApp(${builtins.toJSON binding.apps}) end)''
    else
      ''hyper:bind({}, "${binding.key}", function() launchOrFocus("${binding.app}") end)''
  ) bindings;

  # Generate Lua code for window bindings
  windowBindings = userSettings.hammerspoonWindowBindings or {};

  # Default Hammerspoon init.lua content
  defaultConfig = ''
    -- Hammerspoon Configuration
    -- Generated by Nix Home Manager
    -- Hyperkey = Cmd + Ctrl + Alt + Shift

    -- Reload config automatically when saved
    function reloadConfig(files)
      local doReload = false
      for _,file in pairs(files) do
        if file:sub(-4) == ".lua" then
          doReload = true
        end
      end
      if doReload then
        hs.reload()
      end
    end
    hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", reloadConfig):start()
    hs.alert.show("Hammerspoon Config Loaded")

    -- Hyperkey modal (Cmd+Ctrl+Alt+Shift)
    hyper = hs.hotkey.modal.new({}, nil)
    hyper.pressed = function() hyper:enter() end
    hyper.released = function() hyper:exit() end

    -- Bind F18 as the hyperkey trigger (requires Karabiner or similar)
    -- Alternative: use a specific key combo
    pressedHyper = function() hyper:enter() end
    releasedHyper = function() hyper:exit() end

    -- Create hyperkey binding with Cmd+Ctrl+Alt+Shift
    hs.hotkey.bind({"cmd", "ctrl", "alt", "shift"}, "space", pressedHyper, releasedHyper)

    -- Helper function to launch or focus an app
    function launchOrFocus(appName)
      local app = hs.application.get(appName)
      if app then
        app:activate()
      else
        hs.application.launchOrFocus(appName)
      end
    end

    -- Helper function to cycle through app windows
    function cycleApp(appNames)
      local frontApp = hs.application.frontmostApplication()
      local frontAppName = frontApp:name()

      -- Find current app index in the list
      local currentIndex = 0
      for i, name in ipairs(appNames) do
        if name == frontAppName then
          currentIndex = i
          break
        end
      end

      -- Cycle to next app or first if not in list/at end
      local nextIndex = currentIndex % #appNames + 1
      launchOrFocus(appNames[nextIndex])
    end

    -- ============================================================================
    -- APP BINDINGS
    -- ============================================================================
    ${generateAppBindings (userSettings.hammerspoonAppBindings or [])}

    -- ============================================================================
    -- WINDOW MANAGEMENT
    -- ============================================================================

    -- Maximize window
    hyper:bind({}, "${windowBindings.maximize or "m"}", function()
      local win = hs.window.focusedWindow()
      if win then
        win:maximize()
      end
    end)

    -- Minimize window
    hyper:bind({}, "${windowBindings.minimize or "h"}", function()
      local win = hs.window.focusedWindow()
      if win then
        win:minimize()
      end
    end)

    -- Move window to previous monitor (left)
    hyper:bind({}, "${windowBindings.moveLeft or "Left"}", function()
      local win = hs.window.focusedWindow()
      if win then
        local screen = win:screen()
        local prevScreen = screen:previous()
        if prevScreen then
          win:moveToScreen(prevScreen)
        end
      end
    end)

    -- Move window to next monitor (right)
    hyper:bind({}, "${windowBindings.moveRight or "Right"}", function()
      local win = hs.window.focusedWindow()
      if win then
        local screen = win:screen()
        local nextScreen = screen:next()
        if nextScreen then
          win:moveToScreen(nextScreen)
        end
      end
    end)

    -- Reload Hammerspoon config
    hyper:bind({}, "${windowBindings.reload or "r"}", function()
      hs.reload()
    end)
  '';

in
lib.mkIf (systemSettings.osType == "darwin" && userSettings.hammerspoonEnable) {
  # Hammerspoon config file
  home.file.".hammerspoon/init.lua" = {
    text = if configVariant == "komi"
           then builtins.readFile ./komi-init.lua
           else defaultConfig;
  };

  # Ensure Hammerspoon launches on login (via launchd)
  # Note: Hammerspoon should be installed via Homebrew cask
  launchd.agents.hammerspoon = {
    enable = true;
    config = {
      Label = "org.hammerspoon.Hammerspoon";
      ProgramArguments = [ "/Applications/Hammerspoon.app/Contents/MacOS/Hammerspoon" ];
      RunAtLoad = true;
      KeepAlive = false;
    };
  };
}
