# Database Credentials Module
# Generates ~/.pgpass, ~/.my.cnf and ~/.redis-credentials for CLI tools + DBeaver.
#
# SECURITY MODEL — read before changing
# -------------------------------------
# These files hold PRODUCTION database passwords, so they must never be written
# through `home.file`. `home.file` materialises the content as a /nix/store path
# and symlinks it into $HOME; the store is world-readable (mode 0444), which
# means every local user and every process on the machine can read the
# passwords. It also breaks .pgpass outright: libpq refuses (silently ignores)
# any .pgpass whose resolved mode is broader than 0600, so the store-symlinked
# version never actually authenticated anything.
#
# Instead, profiles pass the NAME of the attribute in secrets/domains.nix
# (`passwordSecret`), never the value. The activation script below resolves
# those names at RUNTIME with `nix eval` and writes real files with mode 0600.
# Nothing secret is ever interpolated into a derivation.
#
#   dbCredentialsPostgres = [
#     { database = "plane"; user = "plane"; passwordSecret = "dbPlanePassword"; }
#   ];
#
# The legacy `password = secrets.X` form is still accepted for profiles that
# have not been migrated, but it re-introduces the store leak — prefer
# `passwordSecret`. A build-time warning fires when it is used.

{ config, lib, pkgs, systemSettings, userSettings, ... }:

let
  dbHost = systemSettings.dbCredentialsHost;
  postgresCredentials = systemSettings.dbCredentialsPostgres;
  mariadbCredentials = systemSettings.dbCredentialsMariadb;
  redisPasswordSecret = systemSettings.dbCredentialsRedisPasswordSecret or "";
  redisPasswordLiteral = systemSettings.dbCredentialsRedisPassword or "";

  secretsFile = "${userSettings.dotfilesDir}/secrets/domains.nix";
  nixBin = "${pkgs.nix}/bin/nix";

  esc = lib.escapeShellArg;

  usesLegacyLiteral =
    (lib.any (c: (c.passwordSecret or "") == "") (postgresCredentials ++ mariadbCredentials))
    || (redisPasswordSecret == "" && redisPasswordLiteral != "");

  # Shell snippet resolving one credential into $pw.
  #   - passwordSecret -> looked up at runtime, never in the store
  #   - password       -> legacy literal, already baked into the store
  resolvePw = cred:
    if (cred.passwordSecret or "") != "" then
      ''pw="$(secret ${esc cred.passwordSecret})"''
    else
      ''pw=${esc (cred.password or "")}'';

  pgpassLines = lib.concatMapStringsSep "\n" (cred: ''
    ${resolvePw cred}
    if [ -n "$pw" ]; then
      printf '%s:5432:%s:%s:%s\n' ${esc dbHost} ${esc cred.database} ${esc cred.user} "$pw" >> "$pgpass"
      printf '%s:6432:%s:%s:%s\n' ${esc dbHost} ${esc cred.database} ${esc cred.user} "$pw" >> "$pgpass"
    fi
  '') postgresCredentials;

  firstMariadb =
    if (builtins.length mariadbCredentials) > 0
    then builtins.head mariadbCredentials
    else null;

  mycnfBlock = lib.optionalString (firstMariadb != null) ''
    ${resolvePw firstMariadb}
    if [ -n "$pw" ]; then
      {
        printf '# MariaDB client configuration — generated by Home Manager (mode 0600)\n\n'
        printf '[client]\nhost = %s\nport = 3306\nuser = %s\npassword = %s\n\n' \
          ${esc dbHost} ${esc firstMariadb.user} "$pw"
        printf '[mysql]\ndatabase = %s\n\n' ${esc firstMariadb.database}
        printf '[mysqldump]\nhost = %s\nport = 3306\nuser = %s\npassword = %s\n' \
          ${esc dbHost} ${esc firstMariadb.user} "$pw"
      } >> "$mycnf"
    fi
  '';

  redisWrite = ''
    if [ -n "$pw" ]; then
      {
        printf '# Redis connection details — generated by Home Manager (mode 0600)\n'
        printf '# Usage: source ~/.redis-credentials, then use the redis-db alias\n'
        printf 'REDIS_HOST=%s\n' ${esc dbHost}
        printf 'REDIS_PORT=6379\n'
        printf 'REDIS_PASSWORD=%s\n' "$pw"
      } >> "$rediscreds"
    fi
  '';

  redisBlock =
    if redisPasswordSecret != "" then ''
      pw="$(secret ${esc redisPasswordSecret})"
      ${redisWrite}
    ''
    else lib.optionalString (redisPasswordLiteral != "") ''
      pw=${esc redisPasswordLiteral}
      ${redisWrite}
    '';

in
lib.mkIf systemSettings.dbCredentialsEnable {
  warnings = lib.optional usesLegacyLiteral ''
    db-credentials: one or more entries still use the literal `password = secrets.X`
    form. That bakes the password into a world-readable /nix/store path. Switch
    the profile to `passwordSecret = "X"` (the attribute NAME) instead.
  '';

  # Written at activation, not via home.file, so the secrets never enter the
  # store and the files get the 0600 that libpq/mysql actually require.
  home.activation.dbCredentials = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    pgpass="$HOME/.pgpass"
    mycnf="$HOME/.my.cnf"
    rediscreds="$HOME/.redis-credentials"

    # Older generations left 0444 /nix/store symlinks here — drop them first.
    for f in "$pgpass" "$mycnf" "$rediscreds"; do
      if [ -L "$f" ]; then rm -f "$f"; fi
    done

    secret() {
      if [ ! -r ${esc secretsFile} ]; then printf ''' ; return; fi
      ${nixBin} eval --impure --raw --expr "(import ${secretsFile}).$1 or \"\"" 2>/dev/null || printf '''
    }

    umask 077

    : > "$pgpass"
    chmod 0600 "$pgpass"
    {
      printf '# PostgreSQL password file — generated by Home Manager (mode 0600)\n'
      printf '# Format: hostname:port:database:username:password\n'
      printf '# Port 5432 = direct PostgreSQL, 6432 = PgBouncer\n'
    } >> "$pgpass"
    ${pgpassLines}
    chmod 0600 "$pgpass"

    ${lib.optionalString (firstMariadb != null) ''
      : > "$mycnf"
      chmod 0600 "$mycnf"
      ${mycnfBlock}
      chmod 0600 "$mycnf"
    ''}

    ${lib.optionalString (redisBlock != "") ''
      : > "$rediscreds"
      chmod 0600 "$rediscreds"
      ${redisBlock}
      chmod 0600 "$rediscreds"
    ''}

    unset pw
  '';

  # Shell shortcuts. NOTE: the redis one deliberately does NOT inline the
  # password — passing it as `redis-cli -a <secret>` would both bake it into the
  # store-resident .zshrc and expose it in `ps` output to every local user.
  programs.zsh.shellAliases = {
    "psql-plane" = "psql -h ${dbHost} -U plane -d plane";
    "psql-liftcraft" = "psql -h ${dbHost} -U liftcraft -d rails_database_prod";
    "mysql-nextcloud" = "mysql -h ${dbHost} -u nextcloud nextcloud";
    "redis-db" = "sh -c '. \"$HOME/.redis-credentials\" && REDISCLI_AUTH=\"$REDIS_PASSWORD\" redis-cli -h \"$REDIS_HOST\" -p \"$REDIS_PORT\"'";
  };
}
