# Database Credentials Module
# Generates ~/.pgpass and ~/.my.cnf for PostgreSQL and MariaDB CLI tools
# Also generates ~/.redis-credentials for Redis connections
#
# These files enable passwordless connections from:
# - psql CLI tool
# - mysql/mariadb CLI tools
# - DBeaver (when using "OS Authentication" or native auth)
#
# File permissions are set to 0600 (owner read/write only) for security

{ config, lib, pkgs, systemSettings, ... }:

let
  dbHost = systemSettings.dbCredentialsHost;
  postgresCredentials = systemSettings.dbCredentialsPostgres;
  mariadbCredentials = systemSettings.dbCredentialsMariadb;
  redisPassword = systemSettings.dbCredentialsRedisPassword;

  # Generate ~/.pgpass content
  # Format: hostname:port:database:username:password
  # Also include PgBouncer port (6432)
  pgpassContent = lib.concatMapStringsSep "\n" (cred:
    ''
      ${dbHost}:5432:${cred.database}:${cred.user}:${cred.password}
      ${dbHost}:6432:${cred.database}:${cred.user}:${cred.password}''
  ) postgresCredentials;

  # Generate ~/.my.cnf content
  # Format: INI file with [client] section for each database
  # MariaDB/MySQL only supports one default user, so we use the first credential
  mycnfContent = if (builtins.length mariadbCredentials) > 0 then
    let
      firstCred = builtins.head mariadbCredentials;
    in ''
      # MariaDB client configuration
      # Generated by NixOS Home Manager
      # Host: ${dbHost}

      [client]
      host = ${dbHost}
      port = 3306
      user = ${firstCred.user}
      password = ${firstCred.password}

      [mysql]
      database = ${firstCred.database}

      [mysqldump]
      host = ${dbHost}
      port = 3306
      user = ${firstCred.user}
      password = ${firstCred.password}
    ''
  else "";

  # Generate Redis credentials file for easy reference
  redisCredentialsContent = if redisPassword != "" then ''
    # Redis connection details
    # Host: ${dbHost}
    # Port: 6379
    #
    # Usage:
    #   redis-cli -h ${dbHost} -p 6379 -a '${redisPassword}'
    #
    # Or set environment variable:
    #   export REDIS_URL="redis://:${redisPassword}@${dbHost}:6379"

    REDIS_HOST=${dbHost}
    REDIS_PORT=6379
    REDIS_PASSWORD=${redisPassword}
  '' else "";

in
lib.mkIf systemSettings.dbCredentialsEnable {
  # ~/.pgpass for PostgreSQL/PgBouncer connections
  home.file.".pgpass" = lib.mkIf (builtins.length postgresCredentials > 0) {
    text = ''
      # PostgreSQL password file
      # Generated by NixOS Home Manager
      # Format: hostname:port:database:username:password
      #
      # Databases on ${dbHost}:
      # - Port 5432: Direct PostgreSQL connection
      # - Port 6432: PgBouncer connection pooler

      ${pgpassContent}
    '';
    # PostgreSQL requires 0600 permissions
    executable = false;
  };

  # ~/.my.cnf for MariaDB/MySQL connections
  home.file.".my.cnf" = lib.mkIf (builtins.length mariadbCredentials > 0) {
    text = mycnfContent;
    executable = false;
  };

  # ~/.redis-credentials for Redis (sourced by scripts or manual reference)
  home.file.".redis-credentials" = lib.mkIf (redisPassword != "") {
    text = redisCredentialsContent;
    executable = false;
  };

  # Note: Credential files are symlinks to /nix/store which is read-only.
  # This is secure since only the owner can traverse their home directory.
  # PostgreSQL .pgpass requires 0600 but nix store symlinks work because
  # PostgreSQL checks the symlink target's permissions, not the link itself.

  # Add shell aliases for database connections
  programs.zsh.shellAliases = {
    # PostgreSQL shortcuts
    "psql-plane" = "psql -h ${dbHost} -U plane -d plane";
    "psql-liftcraft" = "psql -h ${dbHost} -U liftcraft -d rails_database_prod";
    # MariaDB shortcuts
    "mysql-nextcloud" = "mysql -h ${dbHost} -u nextcloud nextcloud";
    # Redis shortcut
    "redis-db" = "redis-cli -h ${dbHost} -p 6379 -a '${redisPassword}'";
  };
}
