"""Render the include file from state, validate it, install it, reload sway."""
from __future__ import annotations

import datetime as _dt
import os
import tempfile
from pathlib import Path

from . import log, paths, swayipc
from . import monitors as _monitors
from .rules import Rule
from .state import State

_log = log.get("generate")

HEADER = """# Generated by sway-apps -- DO NOT EDIT BY HAND.
# Source of truth: {state_dir} (common.json + {profile}.json)
# Regenerate: sway-apps apply
# Generated: {stamp}
"""


def render(state: State, include_disabled: bool = False) -> str:
    lines = [HEADER.format(state_dir=paths.STATE_DIR, profile=paths.profile_name(),
                           stamp=_dt.datetime.now().isoformat(timespec="seconds"))]
    geometry, _notes = _monitors.render_geometry(state)
    if geometry:
        lines.append(geometry)
    pins = _monitors.render_pins(state)
    if pins:
        lines.append(pins)
    by_kind = {"assign": [], "no_focus": [], "for_window": []}
    for r in state.resolved_rules():
        if not r.enabled and not include_disabled:
            continue
        if r.problems():
            _log.warning("skipping invalid rule %s: %s", r.id, "; ".join(r.problems()))
            continue
        by_kind[r.kind].append(r)
    for kind, title in (("assign", "Workspace assignments"), ("no_focus", "No-focus"), ("for_window", "Window rules")):
        rules = by_kind[kind]
        if not rules:
            continue
        lines.append(f"\n# ---- {title} ({len(rules)})")
        for r in rules:
            # i3/sway have no end-of-line comments: the label goes above.
            lines.append(f"# {r.name} [{r.id}]" + ("" if r.enabled else " (disabled)"))
            prefix = "" if r.enabled else "# "
            lines.append(f"{prefix}{r.render()}")
    return "\n".join(lines) + "\n"


def validate(text: str) -> tuple[bool, str]:
    return swayipc.validate_config_text(text)


def install(text: str, target: Path | None = None) -> Path:
    target = target or paths.INCLUDE_FILE
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=".sway-apps-", suffix=".conf")
    with os.fdopen(fd, "w") as fh:
        fh.write(text)
    os.chmod(tmp, 0o644)
    os.replace(tmp, target)
    _log.info("installed %s (%d lines)", target, text.count("\n"))
    return target


def apply(state: State, reload: bool = True, do_validate: bool = True) -> dict:
    """render -> validate -> install -> reload. Raises on validation failure."""
    with log.action("apply", reload=reload, validate=do_validate) as res:
        text = render(state)
        res["rules"] = sum(1 for r in state.rules() if r.enabled)
        if do_validate:
            ok, out = validate(text)
            res["validated"] = ok
            if not ok:
                raise RuntimeError(f"generated config failed validation:\n{out}")
        path = install(text)
        res["path"] = str(path)
        if reload:
            if swayipc.available():
                swayipc.reload()
                res["reloaded"] = True
            else:
                _log.warning("sway socket not available; include written, reload skipped")
                res["reloaded"] = False
        return {"path": str(path), "rules": res["rules"], "reloaded": res.get("reloaded", False)}


def apply_live(rule: Rule, state: State | None = None) -> list[dict]:
    """Run the rule's actions against currently mapped matching windows.
    With `state`, a symbolic target is resolved to this machine's number."""
    if state is not None and rule.target:
        n, _prob = state.resolve_target(rule)
        if n is not None:
            rule = rule.with_workspace_number(n)
    cmds = rule.live_commands()
    hits = []
    if not cmds:
        return hits
    with log.action("apply_live", rule=rule.id) as res:
        for w in swayipc.windows():
            if not swayipc.window_matches(w, rule.criteria):
                continue
            for c in cmds:
                try:
                    swayipc.command(f"[con_id={w.id}] {c}")
                    hits.append({"window": w.id, "label": w.label, "command": c, "ok": True})
                except swayipc.SwayError as exc:
                    hits.append({"window": w.id, "label": w.label, "command": c, "ok": False, "error": str(exc)})
                    _log.warning("live apply failed on %s (%s): %s", w.id, w.label, exc)
        res["matched"] = len({h["window"] for h in hits})
    return hits
