{
  pkgs,
  pkgs-unstable,
  userSettings,
  lib,
  ...
}:

{
  # /bin/bash compatibility symlink
  # Many Wine/Proton wrapper scripts (e.g. generated by Jackify/Wabbajack)
  # use #!/bin/bash which doesn't exist on NixOS by default
  system.activationScripts.binbash = lib.stringAfter [ "binsh" ] ''
    ln -sfn ${pkgs.bash}/bin/bash /bin/bash
  '';

  # Steam configuration
  # Controlled by user variable 'steamPackEnable'
  # Maintains system-level integration (firewall, udev, hardware)

  programs.steam = lib.mkIf (userSettings.steamPackEnable == true) {
    enable = true;
    protontricks.enable = true;
    remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
    dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
    localNetworkGameTransfers.openFirewall = true; # Open ports in the firewall for Steam Local Network Game Transfers
    gamescopeSession.enable = false; # Disabled: designed for Steam Deck DRM sessions, conflicts with nested Wayland gamescope under Sway
    extraPackages =
      [
        # UNSTABLE, deliberately. Steam runs in an FHS environment and resolves
        # gamescope from here, not from PATH — so a home.packages override is
        # invisible to it and restarting Steam changes nothing. `pkgs` is
        # nixpkgs-stable (nixos-25.11), still on 3.16.17, which is the version
        # whose Wayland backend aborts mid-launch (SIGABRT in
        # CWaylandInputThread::ThreadFunc) and whose --force-grab-cursor causes
        # multi-second freezes (upstream #1851). Unstable is on 3.16.28.
        pkgs-unstable.gamescope
      ]
      ++ (with pkgs; [
        mangohud # FPS/performance overlay
      ])
      ++ lib.optionals (userSettings.vkbasaltEnable or false) [
        # Vulkan post-processing layer. Must live in Steam's FHS env for the
        # implicit layer manifest to be discoverable. Opt-in per game via
        # ENABLE_VKBASALT=1 (config: user/app/gaming/vkbasalt.nix).
        pkgs.vkbasalt
      ];
  };

  # gamescope logs this on every launch:
  #
  #   No CAP_SYS_NICE, falling back to regular-priority compute and threads.
  #   Performance will be affected.
  #
  # ‼️ DO NOT fix that with `programs.gamescope.capSysNice = true`. Tried
  # 2026-09-04: the NixOS security wrapper raises capabilities on exec, and Steam
  # starts its children under no_new_privs, so the wrapper dies immediately with
  #
  #   failed to inherit capabilities: Operation not permitted
  #
  # and gamescope exits rc=1 before the game ever appears. The capability route
  # only works for a gamescope launched outside Steam. If realtime priority is
  # worth chasing again, do it through RLIMIT_RTPRIO (security.pam.loginLimits)
  # and verify the message actually disappears, rather than through a wrapper in
  # Steam's PATH.

  nixpkgs.config.allowUnfreePredicate =
    pkg:
    builtins.elem (lib.getName pkg) [
      "steam"
      "steam-original"
      "steam-unwrapped"
      "steam-run"
    ];

}
