{
  pkgs,
  userSettings,
  lib,
  ...
}:

{
  # /bin/bash compatibility symlink
  # Many Wine/Proton wrapper scripts (e.g. generated by Jackify/Wabbajack)
  # use #!/bin/bash which doesn't exist on NixOS by default
  system.activationScripts.binbash = lib.stringAfter [ "binsh" ] ''
    ln -sfn ${pkgs.bash}/bin/bash /bin/bash
  '';

  # Steam configuration
  # Controlled by user variable 'steamPackEnable'
  # Maintains system-level integration (firewall, udev, hardware)

  programs.steam = lib.mkIf (userSettings.steamPackEnable == true) {
    enable = true;
    protontricks.enable = true;
    remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
    dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
    localNetworkGameTransfers.openFirewall = true; # Open ports in the firewall for Steam Local Network Game Transfers
    gamescopeSession.enable = true; # Gamescope compositor session (Steam Deck-like from login screen)
    extraPackages = with pkgs; [
      gamescope # Nested Wayland compositor for per-game scaling
      mangohud # FPS/performance overlay
    ];
  };

  nixpkgs.config.allowUnfreePredicate =
    pkg:
    builtins.elem (lib.getName pkg) [
      "steam"
      "steam-original"
      "steam-unwrapped"
      "steam-run"
    ];

}
