#!/usr/bin/env python3
"""
Workspace Groups GUI - Assign swaysome groups to monitors
Saves to ~/.config/sway/workspace-groups.conf
"""

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import subprocess
import json
import os

CONFIG_PATH = os.path.expanduser("~/.config/sway/workspace-groups.conf")

def get_monitors():
    """Get list of connected monitors from swaymsg"""
    try:
        result = subprocess.run(
            ["swaymsg", "-t", "get_outputs"],
            capture_output=True, text=True
        )
        outputs = json.loads(result.stdout)
        return [
            {
                "name": o["name"],
                "make": o.get("make", ""),
                "model": o.get("model", ""),
                "serial": o.get("serial", ""),
                "active": o.get("active", False)
            }
            for o in outputs if o.get("active", False)
        ]
    except Exception as e:
        print(f"Error getting monitors: {e}")
        return []

def get_hardware_id(monitor):
    """Generate hardware ID string for monitor"""
    parts = [monitor["make"], monitor["model"], monitor["serial"]]
    return " ".join(p for p in parts if p).strip()

def get_display_name(monitor):
    """Get a user-friendly display name for monitor"""
    if monitor["model"]:
        return monitor["model"]
    elif monitor["make"]:
        return f"{monitor['make']} ({monitor['name']})"
    else:
        return monitor["name"]

def load_config():
    """Load existing workspace-groups.conf"""
    config = {}
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, val = line.rsplit('=', 1)
                    config[key.strip()] = val.strip()
    return config

def save_config(assignments, auto_assign=True):
    """Save workspace-groups.conf"""
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    with open(CONFIG_PATH, 'w') as f:
        f.write("# Workspace Group Configuration\n")
        f.write("# Format: MONITOR_HARDWARE_ID=GROUP_NUMBER\n")
        f.write("# Generated by workspace-groups-gui\n\n")
        for hw_id, group in sorted(assignments.items()):
            f.write(f"{hw_id}={group}\n")
        f.write("\n")
        if auto_assign:
            f.write("# Auto-assign unknown monitors\n*=auto\n")

def apply_groups():
    """Run swaysome-assign-groups.sh to apply changes"""
    script = os.path.expanduser("~/.config/sway/scripts/swaysome-assign-groups.sh")
    if os.path.exists(script):
        try:
            subprocess.run([script], check=False)
        except Exception as e:
            print(f"Error applying groups: {e}")

class WorkspaceGroupsWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Workspace Groups")
        self.set_default_size(550, 350)
        self.set_border_width(20)
        self.set_position(Gtk.WindowPosition.CENTER)

        self.monitors = get_monitors()
        self.config = load_config()
        self.combos = {}

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
        self.add(vbox)

        # Header
        header = Gtk.Label()
        header.set_markup("<b>Assign Workspace Groups to Monitors</b>")
        vbox.pack_start(header, False, False, 10)

        # Description
        desc = Gtk.Label()
        desc.set_markup("<small>Each group contains workspaces 1-10 for that monitor.\nGroup 1 = WS 11-20, Group 2 = WS 21-30, etc.</small>")
        desc.set_line_wrap(True)
        vbox.pack_start(desc, False, False, 5)

        # Separator
        vbox.pack_start(Gtk.Separator(), False, False, 5)

        # Monitor rows
        if not self.monitors:
            no_mon = Gtk.Label(label="No active monitors detected")
            vbox.pack_start(no_mon, True, True, 0)
        else:
            grid = Gtk.Grid()
            grid.set_column_spacing(20)
            grid.set_row_spacing(10)
            grid.set_halign(Gtk.Align.CENTER)
            vbox.pack_start(grid, True, True, 0)

            # Column headers
            mon_header = Gtk.Label()
            mon_header.set_markup("<b>Monitor</b>")
            mon_header.set_halign(Gtk.Align.START)
            grid.attach(mon_header, 0, 0, 1, 1)

            group_header = Gtk.Label()
            group_header.set_markup("<b>Group</b>")
            group_header.set_halign(Gtk.Align.START)
            grid.attach(group_header, 1, 0, 1, 1)

            ws_header = Gtk.Label()
            ws_header.set_markup("<b>Workspaces</b>")
            ws_header.set_halign(Gtk.Align.START)
            grid.attach(ws_header, 2, 0, 1, 1)

            for i, mon in enumerate(self.monitors):
                hw_id = get_hardware_id(mon)
                display_name = get_display_name(mon)

                # Monitor label
                label = Gtk.Label(label=display_name)
                label.set_halign(Gtk.Align.START)
                label.set_max_width_chars(35)
                label.set_ellipsize(3)  # PANGO_ELLIPSIZE_END
                label.set_tooltip_text(f"Hardware ID: {hw_id}\nConnector: {mon['name']}")
                grid.attach(label, 0, i + 1, 1, 1)

                # Group dropdown
                combo = Gtk.ComboBoxText()
                for g in range(1, 11):
                    combo.append_text(f"Group {g}")

                # Set current value from config
                current = self.config.get(hw_id, str(i + 1))
                if current.isdigit():
                    combo.set_active(int(current) - 1)
                else:
                    combo.set_active(i)

                combo.connect("changed", self.on_combo_changed, i)
                grid.attach(combo, 1, i + 1, 1, 1)
                self.combos[hw_id] = (combo, i)

                # Workspace range label
                ws_label = Gtk.Label()
                self.update_ws_label(ws_label, combo.get_active() + 1)
                grid.attach(ws_label, 2, i + 1, 1, 1)
                self.combos[hw_id] = (combo, ws_label)

        # Separator
        vbox.pack_start(Gtk.Separator(), False, False, 5)

        # Auto-assign checkbox
        self.auto_check = Gtk.CheckButton(label="Auto-assign unknown monitors")
        self.auto_check.set_active(self.config.get('*', '') == 'auto')
        self.auto_check.set_tooltip_text("Automatically assign group numbers to new monitors")
        vbox.pack_start(self.auto_check, False, False, 10)

        # Buttons
        button_box = Gtk.Box(spacing=10)
        button_box.set_halign(Gtk.Align.END)
        vbox.pack_start(button_box, False, False, 0)

        cancel_btn = Gtk.Button(label="Cancel")
        cancel_btn.connect("clicked", lambda x: self.destroy())
        button_box.pack_start(cancel_btn, False, False, 0)

        apply_btn = Gtk.Button(label="Apply")
        apply_btn.get_style_context().add_class("suggested-action")
        apply_btn.connect("clicked", self.on_apply)
        button_box.pack_start(apply_btn, False, False, 0)

    def update_ws_label(self, label, group):
        """Update workspace range label for a group"""
        ws_start = group * 10 + 1
        ws_end = group * 10 + 10
        label.set_markup(f"<small>WS {ws_start}-{ws_end}</small>")

    def on_combo_changed(self, combo, row_index):
        """Update workspace label when combo changes"""
        group = combo.get_active() + 1
        # Find the corresponding workspace label
        for hw_id, (c, ws_label) in self.combos.items():
            if c == combo:
                self.update_ws_label(ws_label, group)
                break

    def on_apply(self, button):
        assignments = {}
        for hw_id, (combo, _) in self.combos.items():
            group = combo.get_active() + 1
            assignments[hw_id] = str(group)

        save_config(assignments, self.auto_check.get_active())
        apply_groups()

        # Show confirmation
        dialog = Gtk.MessageDialog(
            transient_for=self,
            flags=0,
            message_type=Gtk.MessageType.INFO,
            buttons=Gtk.ButtonsType.OK,
            text="Workspace groups updated"
        )
        dialog.format_secondary_text("The configuration has been saved and applied.")
        dialog.run()
        dialog.destroy()

        self.destroy()

def main():
    win = WorkspaceGroupsWindow()
    win.connect("destroy", Gtk.main_quit)
    win.show_all()
    Gtk.main()

if __name__ == "__main__":
    main()
