{ config, pkgs, lib, systemSettings, userSettings, pkgs-unstable ? pkgs, ... }:

{
    # Volume/brightness OSD (matches Hyprland behavior)
    services.swayosd = {
      enable = true;
      topMargin = 0.5;
    };

    # Systemd-first Sway session daemons (scalable relog fix)
    #
    # We bind session daemons to a dedicated target started from Sway.
    # This avoids lock/race issues from the legacy custom daemon manager and prevents leakage into Plasma 6.
    #
    # Stylix containment: services read session-scoped vars from %t/sway-session.env written by Sway.
    systemd.user.targets."sway-session" = {
      Unit = {
        BindsTo = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
      };
      Install = {
        WantedBy = [];
      };
    };

    # NOTE: No systemd service here: `xkb_numlock` is config-only (IPC toggling is rejected by Sway).

    # Waybar is generated by Home Manager (programs.waybar.systemd.enable = true), but we override wiring:
    # - bind to sway-session.target (not graphical-session.target)
    # - load env vars from %t/sway-session.env
    systemd.user.services.waybar = {
      Unit = {
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" "graphical-session.target" ];
      };
      Service = {
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = lib.mkForce [ "sway-session.target" ];
      };
    };

    # Custom idle inhibit lock (for a reliable toggle from keybindings + Waybar custom module).
    # This is separate from Waybar's built-in idle_inhibitor module so we can test safely.
    systemd.user.services."idle-inhibit" = {
      Unit = {
        Description = "Idle inhibit lock (custom toggle)";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "${pkgs.systemd}/bin/systemd-inhibit --what=idle --who=IdleToggle --why=Idle_inhibited ${pkgs.coreutils}/bin/sleep infinity";
        Restart = "no";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        # Do not autostart; toggled by script/keybinding.
        WantedBy = [];
      };
    };

    systemd.user.services.swaync = {
      Unit = {
        Description = "Sway Notification Center";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.swaynotificationcenter}/bin/swaync";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };

    # nm-applet: define a complete unit (ExecStart is required).
    # We keep ordering `After=waybar.service` so tray registration is deterministic.
    systemd.user.services."nm-applet" = {
      Unit = {
        Description = "NetworkManager Applet";
        PartOf = [ "sway-session.target" ];
        Wants = [ "waybar.service" ];
        After = [ "sway-session.target" "waybar.service" ];
      };
      Service = {
        ExecStart = "${pkgs.networkmanagerapplet}/bin/nm-applet --indicator";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = lib.mkForce [ "sway-session.target" ];
      };
    };

    # Home Manager's `services.blueman-applet` defines `systemd.user.services.blueman-applet`.
    # Avoid conflicting leaves (like Unit.Description / ExecStart) by only overriding:
    # - binding to sway-session.target (so it won't start in Plasma 6)
    # - tray ordering (After/Wants waybar.service)
    # - session env file
    systemd.user.services."blueman-applet" = {
      Unit = {
        PartOf = [ "sway-session.target" ];
        Wants = [ "waybar.service" ];
        After = [ "sway-session.target" "waybar.service" ];
      };
      Service = {
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = lib.mkForce [ "sway-session.target" ];
      };
    };

    systemd.user.services.cliphist = {
      Unit = {
        Description = "Cliphist watcher (wl-paste)";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.wl-clipboard}/bin/wl-paste --watch ${pkgs.cliphist}/bin/cliphist store";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };

    systemd.user.services.kwalletd6 = {
      Unit = {
        Description = "KWallet daemon (Qt6)";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.kdePackages.kwallet}/bin/kwalletd6";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };

    systemd.user.services."libinput-gestures" = lib.mkIf (
      lib.hasInfix "laptop" (lib.toLower systemSettings.hostname) ||
      lib.hasInfix "yoga" (lib.toLower systemSettings.hostname)
    ) {
      Unit = {
        Description = "libinput-gestures";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.libinput-gestures}/bin/libinput-gestures";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };

    systemd.user.services.sunshine = lib.mkIf (systemSettings.sunshineEnable == true) {
      Unit = {
        Description = "Sunshine (tray-ordered)";
        PartOf = [ "sway-session.target" ];
        Wants = [ "waybar.service" ];
        After = [ "sway-session.target" "waybar.service" ];
      };
      Service = {
        ExecStart = "${pkgs.sunshine}/bin/sunshine";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };

    systemd.user.services.swaybg = lib.mkIf (
      systemSettings.stylixEnable == true
      && (systemSettings.swaybgPlusEnable or false) != true
      && (systemSettings.swwwEnable or false) != true
      && (userSettings.wm != "plasma6" || systemSettings.enableSwayForDESK == true)
    ) {
      Unit = {
        Description = "swaybg (Stylix wallpaper)";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.swaybg}/bin/swaybg -i ${config.stylix.image} -m fill";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };

    # Nextcloud Desktop Client: starts in background when Sway session begins
    systemd.user.services."nextcloud-client" = lib.mkIf (systemSettings.nextcloudEnable == true) {
      Unit = {
        Description = "Nextcloud Desktop Client";
        PartOf = [ "sway-session.target" ];
        After = [ "sway-session.target" "waybar.service" ];
        Wants = [ "waybar.service" ];
      };
      Service = {
        ExecStart = "${pkgs-unstable.nextcloud-client}/bin/nextcloud --background";
        Restart = "on-failure";
        RestartSec = "2s";
        EnvironmentFile = [ "-%t/sway-session.env" ];
      };
      Install = {
        WantedBy = [ "sway-session.target" ];
      };
    };
}


